import { DM_Sans } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "./context/AuthContext";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${dmSans.variable}`}>
      <body className="font-sans">
        <AuthContextProvider>
        {children}
        </AuthContextProvider>
      </body>
    </html>
      
  );
}
